Disable Tinylog WritingThread due to it crashing.
Tinylog WritingThread crashes with
java.lang.OutOfMemoryError: Java heap space
at org.tinylog.core.WritingThread.add(WritingThread.java:90)
if logging is called too often because the writing thread only writes
out every 10ms instead of whenever there is messages to log.